before_script:
    - env | sort

.deploy_template: &deploy_template
  stage: deploy
  script:
    - docker-compose up -d  --force-recreate --build
    - docker rmi $(docker images --filter "dangling=true" -q --no-trunc) || echo "Fail!"
    - echo 'Successfully deploy'

deploy_dev:
  <<: *deploy_template
  tags:
    - dev-shell
  only:
    - dev
    - /^devops\/.*$/

deploy_prod:
  <<: *deploy_template
  tags:
    - prod-shell
  only:
    - master

deploy_prod_devops:
  <<: *deploy_template
  tags:
    - prod-shell
  only:
    - /^devops\/.*$/
  when: manual
