before_script:
    - env | sort


deploy_dev:
  stage: deploy
  script:
    - mv -f .env.development .env
    - find . -type f -iname ".env.*" -not -name '.env' -delete
    - docker-compose up -d  --force-recreate --build
    - docker rmi $(docker images --filter "dangling=true" -q --no-trunc) || echo "Fail!"
    - echo 'Successfully deploy'
  tags:
    - dev-shell
  only:
    - develop
    - /^devops\/dev.*$/

deploy_prod:
  stage: deploy
  script:
    - mv -f .env.production .env
    - find . -type f -iname ".env.*" -not -name '.env' -delete
    - docker-compose -f docker-compose-prod.yml up -d  --force-recreate --build
    - docker rmi $(docker images --filter "dangling=true" -q --no-trunc) || echo "Fail!"
    - echo 'Successfully deploy'
  tags:
    - prod-shell
  only:
    - master
    - /^devops\/prod.*$/
