before_script:
    - env | sort


deploy_dev:
  stage: deploy
  script:
    - docker-compose up -d  --force-recreate --build
    - docker rmi $(docker images --filter "dangling=true" -q --no-trunc) || echo "Fail!"
    - echo 'Successfully deploy'
  tags:
    - dev-shell
  only:
    - develop
    - /^devops\/dev.*$/

deploy_prod:
  stage: deploy
  script:
    - docker-compose up -f docker-compose-prod.yml -d  --force-recreate --build
    - docker rmi $(docker images --filter "dangling=true" -q --no-trunc) || echo "Fail!"
    - echo 'Successfully deploy'
  tags:
    - prod-shell
  only:
    - master
    - /^devops\/prod.*$/
