version: "3.7"

services:

  front:
    restart: always
    image: ddemo-front
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - ddemo
    volumes:
      - /opt/ddemo/storage/app/public:/usr/src/app/public


  nginx-ingress:
    restart: always
    image: nginx:alpine
    container_name: nginx
    networks:
      - ddemo
    volumes:
      - ./nginx/app.prod.conf:/etc/nginx/conf.d/default.conf
      - /opt/ddemo/storage/app/public:/usr/share/nginx/html/storage
      - /opt/letsencrypt:/var/www/_letsencrypt
      - /etc/letsencrypt/:/ssl/
    ports:
      - 80:80
      - 443:443
networks:
  ddemo:
