version: "3.7"

services:

  front:
    restart: always
    image: ddemo-front
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL}
    networks:
      - ddemo
    volumes:
      - /opt/ddemo/storage/app/public:/usr/share/nginx/html/storage


networks:
  ddemo:
    external: true
