version: "3.7"

services:

  front:
    restart: always
    image: ddemo-front
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - ddemo
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - /opt/ddemo/storage/app/public:/usr/share/nginx/html/storage
      - /opt/ddemo/ssl/fullchain.pem:/ssl/fullchain.pem
      - /opt/ddemo/ssl/privkey.pem:/ssl/privkey.pem
    ports:
      - 80:80
      - 443:443


networks:
  ddemo:
